# Filtro de Kalman

Funções de cálculo das distâncias medidas pelos sensores.

$dF (x, y, \theta) = \begin{matrix} \frac{|Sy - Yp|}{|\cos(\theta)|}, & 0 \le \theta \lt \frac{\pi}{2}  \\ 
          \frac{|Sx - Xp|}{|\sin(\theta)|}, & \frac{\pi}{2} \le \theta \lt \pi \\
          \frac{Yp}{|\cos(\theta)|}, & \pi \le \theta \lt \frac{3\pi}{2}  \\ 
          \frac{Xp}{|\sin(\theta)|}, & \frac{3\pi}{2} \le \theta \lt 2\pi
           \end{matrix} $

$dR (x, y, \theta) = \begin{matrix} \frac{|Sx - Xp|}{|\cos(\theta)|}, & 0 \le \theta \lt \frac{\pi}{2}  \\ 
          \frac{Yp}{|\sin(\theta)|}, & \frac{\pi}{2} \le \theta \lt \pi \\
          \frac{Xp}{|\cos(\theta)|}, & \pi \le \theta \lt \frac{3\pi}{2}  \\ 
          \frac{|Sy - Yp|}{|\sin(\theta)|}, & \frac{3\pi}{2} \le \theta \lt 2\pi
           \end{matrix} $

$dL (x, y, \theta) = \begin{matrix} \frac{Xp}{|\cos(\theta)|}, & 0 \le \theta \lt \frac{\pi}{2}  \\ 
          \frac{|Sy - Yp|}{|\sin(\theta)|}, & \frac{\pi}{2} \le \theta \lt \pi \\
          \frac{Sx - Xp}{|\cos(\theta)|}, & \pi \le \theta \lt \frac{3\pi}{2}  \\ 
          \frac{Yp}{|\sin(\theta)|}, & \frac{3\pi}{2} \le \theta \lt 2\pi
           \end{matrix} $

In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [64]:
def determinarDF(x, y, theta, Sx, Sy):
    dF = 0
    if theta >= 0 and theta < np.pi / 2:
        dF = (Sy - y) / np.abs(np.cos(theta)) 
    elif theta >= np.pi / 2 and theta < np.pi:
        dF = (Sx - x) / np.abs(np.sin(theta))
    elif theta >= np.pi and theta < 3*np.pi/2:
        dF = y / np.abs(np.cos(theta)) 
    elif theta >= 3 * np.pi / 2 and theta < 2 * np.pi:
        dF = x / np.abs(np.sin(theta))        
    return dF

def determinarDR(x, y, theta, Sx, Sy):
    dR = 0
    if theta >= 0 and theta < np.pi / 2:
        dR = (Sx - x) / np.abs(np.cos(theta)) 
    elif theta >= np.pi / 2 and theta < np.pi:
        dR = (Sx - x) / np.abs(np.sin(theta))
    elif theta >= np.pi and theta < 3*np.pi/2:
        dR = x / np.abs(np.cos(theta)) 
    elif theta >= 3 * np.pi / 2 and theta < 2 * np.pi:
        dR = (Sy - y) / np.abs(np.sin(theta))        
    return dR

def determinarDL(x, y, theta, Sx, Sy):
    dL = 0
    if theta >= 0 and theta < np.pi / 2:
        dL = x / np.abs(np.cos(theta)) 
    elif theta >= np.pi / 2 and theta < np.pi:
        dL = (Sy - y) / np.abs(np.sin(theta))
    elif theta >= np.pi and theta < 3*np.pi/2:
        dL = (Sx - x) / np.abs(np.cos(theta)) 
    elif theta >= 3 * np.pi / 2 and theta < 2 * np.pi:
        dL = y / np.abs(np.sin(theta))        
    return dL

    
def determinarMatrizH(x, y, theta, Sx, Sy):
    if theta >= 0 and theta < np.pi / 2:
        H = np.array([[0, -1/np.abs(np.cos(theta)), 0, 0, (((Sy - y)*np.tan(theta)) / np.abs(np.cos(theta)))],
                       [-1/np.abs(np.cos(theta)), 0, 0, 0,(((Sx - x)*np.tan(theta)) / np.abs(np.cos(theta)))],
                       [-1/np.abs(np.cos(theta)), 0, 0, 0, (((x)*np.tan(theta)) / np.abs(np.cos(theta)))],
                       [0, 0, 0, 0, 0],
                       [0, 0, 0, 0, 0]])
    elif theta >= np.pi / 2 and theta < np.pi:
        H = np.array([[-1/np.abs(np.sin(theta)), 0, 0, 0, ((-(Sx - x)*np.cos(theta)) / (np.sin(theta) * np.abs(np.sin(theta))))],
                       [0, 1/np.abs(np.sin(theta)),  0, 0, ((-(y)*np.cos(theta)) / (np.sin(theta) * np.abs(np.sin(theta))))],
                       [0, -1/np.abs(np.sin(theta)), 0, 0, ((-(Sy - y)*np.cos(theta)) / (np.sin(theta) * np.abs(np.sin(theta))))],
                       [0, 0, 0, 0, 0],
                       [0, 0, 0, 0, 0]])
    elif theta >= np.pi and theta < 3*np.pi/2:
        H = np.array([[0, 1/np.abs(np.cos(theta)), 0, 0, (((y)*np.tan(theta)) / np.abs(np.cos(theta)))],
                       [1/np.abs(np.cos(theta)), 0, 0, 0, (((x)*np.tan(theta)) / np.abs(np.cos(theta)))],
                       [-1/np.abs(np.cos(theta)), 0, 0, 0, (((Sx - x)*np.tan(theta)) / np.abs(np.cos(theta)))],
                       [0, 0, 0, 0, 0],
                       [0, 0, 0, 0, 0]])
    elif theta >= 3 * np.pi / 2 and theta < 2 * np.pi:
        H = np.array([[1/np.abs(np.sin(theta)), 0,   0, 0, ((-(x)*np.cos(theta)) / (np.sin(theta) * np.abs(np.sin(theta))))],
                       [0, -1/np.abs(np.sin(theta)),  0, 0, ((-(Sy - y)*np.cos(theta)) / (np.sin(theta) * np.abs(np.sin(theta))))],
                       [0, -1/np.abs(np.sin(theta)), 0, 0, ((-(y)*np.cos(theta)) / (np.sin(theta) * np.abs(np.sin(theta))))],
                       [0, 0, 0, 0, 0],
                       [0, 0, 0, 0, 0]])
    return H

In [65]:
def calculateInverseSk(Sk):
    numeros = []
    matrixSk = []
    for i in range(0, 5):
        for j in range(0, 5):
            if len(np.shape(Sk[i, j])) == 2:
                aux = Sk[i, j][0, 0]
            elif len(np.shape(Sk[i, j])) == 1:
                aux = Sk[i, j][0]
            numeros.append(aux)
        matrixSk.append(numeros.copy())
        numeros.clear()
    novoSk = np.array(matrixSk)
    inversoSk = np.linalg.inv(novoSk)
    return inversoSk
    

In [66]:
def handlePosicao(posicao_atual):
    posicao = []
    for elem in posicao_atual:
        if len(np.shape(elem)) == 2:
            aux = elem[0, 0][0, 0]
        elif len(np.shape(elem)) == 1:
            aux = elem[0][0]
        posicao.append(aux)
    return posicao

In [67]:
def handleP(P_atual):
    numeros = []
    matrixP = []
    for i in range(0, 5):
        for j in range(0, 5):
            if len(np.shape(P_atual[i, j])) == 2:
                aux = P_atual[i, j][0, 0]
            elif len(np.shape(P_atual[i, j])) == 1:
                aux = P_atual[i, j][0]
            numeros.append(aux)
        matrixP.append(numeros.copy())
        numeros.clear()
    novoP = np.array(matrixP)
    return novoP

In [61]:
def filtroDeKalman(posicao_anterior, deltaT, u_k, P, distancias_lidas):
    posicao_anterior = (np.array([posicao_anterior])).transpose()
    x_kmenos1, y_kmenos1, vx_kmenos1, vy_kmenos1, theta_kmenos1 = posicao_anterior[0], posicao_anterior[1], posicao_anterior[2], posicao_anterior[3], posicao_anterior[4] 
    aceleracao_medida, velocidade_angular = u_k[0], u_k[1]
    alpha = theta_kmenos1 + (deltaT*velocidade_angular) 
    deltaX = (1/2 * (deltaT ** 2) * aceleracao_medida  + vx_kmenos1*deltaT) * np.cos(alpha)
    deltaY = (1/2 * (deltaT ** 2) * aceleracao_medida + vy_kmenos1*deltaT) * np.sin(alpha)
    deltaVx = aceleracao_medida * deltaT * np.cos(alpha)
    deltaVy = aceleracao_medida * deltaT * np.sin(alpha)
    deltaTheta = deltaT * velocidade_angular
    posicao_predita = posicao_anterior + np.array([[deltaX],
                                                    [deltaY],
                                                    [deltaVx],
                                                    [deltaVy],
                                                    [deltaTheta]])
    F_p = np.array([[1, 0, deltaT * np.cos(alpha), 0, ((-1/2 * (deltaT ** 2) * aceleracao_medida - vx_kmenos1 * deltaT) * np.sin(alpha))],
                     [0, 1, 0, deltaT * np.sin(alpha), ((1/2 * (deltaT ** 2) * aceleracao_medida + vy_kmenos1 * deltaT) * np.cos(alpha))],
                     [0, 0, 1, 0, (-1)*(aceleracao_medida * deltaT * np.sin(alpha))],
                     [0, 0, 0, 1, (aceleracao_medida * deltaT * np.cos(alpha))],
                     [0, 0, 0, 0, 1]])
    
    F_u = np.array([[1/2 * (deltaT ** 2) * np.cos(alpha), 
                        ((-1/2 * (deltaT ** 3) * aceleracao_medida) - (vx_kmenos1 * (deltaT ** 2))) * np.sin(alpha)],
                     [1/2 * (deltaT ** 2) * np.sin(alpha),
                         ((1/2 * (deltaT ** 3) * aceleracao_medida) + (vy_kmenos1 * (deltaT ** 2))) * np.cos(alpha)],
                     [deltaT * np.cos(alpha), (-1)*(aceleracao_medida * deltaT * np.sin(alpha))],
                     [deltaT * np.sin(alpha), (aceleracao_medida * deltaT * np.cos(alpha))],
                     [0, deltaT]])
    
    Q = np.array([[1, 0],
                   [0, 1]])
    P_predito = (F_p.dot(P)).dot(F_p.transpose()) + (F_u.dot(Q)).dot(F_u.transpose())
    Sx, Sy = 1, 1
    theta = posicao_predita[4][0]
    if theta < 0:
        theta = theta + 2*np.pi
    if theta > 2*np.pi:
        theta = theta - 2*np.pi
    hDF = determinarDF(posicao_predita[0][0], posicao_predita[1][0], theta, Sx, Sy)
    hDR = determinarDR(posicao_predita[0][0], posicao_predita[1][0], theta, Sx, Sy)
    hDL = determinarDL(posicao_predita[0][0], posicao_predita[1][0], theta, Sx, Sy)
    funcaoH = [hDF, hDR, hDL, 0, 0]
    distancias_lidas.append(0)
    distancias_lidas.append(0)
    Vk = np.array([distancias_lidas]).transpose() - np.array([funcaoH]).transpose()
    Hm = determinarMatrizH(posicao_predita[0][0], posicao_predita[1][0], theta, Sx, Sy)
    Rk = np.array([[0.01, 0, 0, 0, 0],
                    [0, 0.01, 0, 0, 0],
                    [0, 0, 0.01, 0, 0],
                    [0, 0, 0, 0.01, 0],
                    [0, 0, 0, 0, 0.01]])
    Sk = (Hm.dot(P_predito)).dot(Hm.transpose()) + Rk
    inversoSk = calculateInverseSk(Sk)
    Kk = (P_predito.dot(Hm.transpose())).dot(inversoSk) 
    posicao_atual = posicao_predita + (Kk.dot(Vk))
    P_atual = P_predito + ((Kk.dot(Sk)).dot(Kk.transpose()))
    return handlePosicao(posicao_atual), handleP(P_atual)

In [68]:
P = np.matrix([[0.1, 0, 0, 0, 0], [0, 0.1, 0, 0, 0], [0, 0, 0.1, 0, 0], [0, 0, 0, 0.1, 0], [0, 0, 0, 0, 0.1]])
posicao_atual, P_atual = filtroDeKalman([0, 0, 0, 0, 0], 1, [0.1, 0], P, [1, 1, 0])
print(posicao_atual)
print("-----------------------------------------------------------------------")
print(P_atual)
print("***********************************************************************")
posicao_atual, P_atual = filtroDeKalman(posicao_atual, 1, [0.1, 0], P_atual, [1, 1, 0])
print(posicao_atual)
print("-----------------------------------------------------------------------")
print(P_atual)

[0.05000000000000016, 0.0, 0.10000000000000016, 0.0, 0.0]
-----------------------------------------------------------------------
[[0.89505495 0.         1.19340659 0.         0.        ]
 [0.         0.19638692 0.         0.0105122  0.10512195]
 [1.19340659 0.         1.89120879 0.         0.        ]
 [0.         0.0105122  0.         0.11126829 0.11268293]
 [0.         0.10512195 0.         0.11268293 1.12682927]]
***********************************************************************
[0.20000000000000034, 0.0, 0.2000000000000059, 0.0, 0.0]
-----------------------------------------------------------------------
[[10.84115845  0.          7.16592885  0.          0.        ]
 [ 0.          0.41488238  0.          0.07290715  0.41341072]
 [ 7.16592885  0.          5.25843159  0.          0.        ]
 [ 0.          0.07290715  0.          0.16133169  0.36085399]
 [ 0.          0.41341072  0.          0.36085399  2.32806022]]


In [70]:
arrayPosicao, arrayP = [], []
arquivoAc = open("arqAccel.txt","r")
arquivoGy = open("arqGyro.txt","r")
arquivoDist = open("arqDist.txt","r")
posicao_atual = [0, 0, 0, 0, 0]
i = 0
P_atual = np.matrix([[0.1, 0, 0, 0, 0], [0, 0.1, 0, 0, 0], [0, 0, 0.1, 0, 0], [0, 0, 0, 0.1, 0], [0, 0, 0, 0, 0.1]])
for accel, gyro, dist in zip(arquivoAc, arquivoGy, arquivoDist):
    arrDist = dist.split(";")
    distances = [int(arrDist[0]), int(arrDist[1]), int(arrDist[2])]
    acc = float(accel)
    gyr = float(gyro)
    posicao_atual, P_atual = filtroDeKalman(posicao_atual, 0.2, [acc, gyr], P_atual, distances)
    arrayPosicao.append(posicao_atual)
    arrayP.append(P_atual)
    i += 1
    print(i)
arquivoAc.close()
arquivoGy.close()
arquivoDist.close()

1
2
3
4


UnboundLocalError: local variable 'H' referenced before assignment